name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v4
        name: 📬 Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        name: ⬢ Install Node.js
        with:
          node-version: lts
          cache: 'yarn'
      - uses: nrwl/nx-set-shas@v4
        name: 🪄 Set nx affected shas
      - run: yarn install
        name: 🔨 Install dependencies
      - run: yarn nx format:check
        name: 💅 Check formatting
      - run: yarn nx affected -t lint --parallel=3
        name: 🧹 Lint
      - run: yarn nx affected -t test --parallel=3 --configuration=ci
        name: 🧪 Test
      - run: yarn nx affected -t build --parallel=3
        name: 🏗 Build
